SELECT AUTHOR.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY, 
SUM(BOOK_SALES.SALES * BOOK.PRICE) AS TOTAL_SALES
FROM AUTHOR
INNER JOIN BOOK ON AUTHOR.AUTHOR_ID = BOOK.AUTHOR_ID
INNER JOIN BOOK_SALES ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC
